// Airtable Configuration
// Auto-generated by app/modules/extensions/hhmi-compliance/scripts/sync-airtable-schema.mts
// Do not edit manually - run the script to update
export const AIRTABLE_CONFIG = {
  baseId: 'appuBoDw7bAfzfyK4',
  tables: {
    publications: {
      name: 'Publications',
      id: 'tblZw5sCSjmxfd4PC',
      fields: {
        abstract_text: {
          name: 'Abstract Text',
          id: 'fld5gJeDcjPzFyfBy',
        },
        action_steps: {
          name: 'Action Steps',
          id: 'fldNlLLohngblRPFw',
        },
        ai_summary_from_abstract: {
          name: 'AI Summary (from Abstract)',
          id: 'fldYAHUAfafLCKR5w',
        },
        all_dates_emailed: {
          name: 'All Dates Emailed',
          id: 'flde5eynS5gPoyKfs',
        },
        attachments: {
          name: 'Attachments',
          id: 'fldd2QnYuvypILygr',
        },
        author_list_standardized: {
          name: 'Author List Standardized',
          id: 'fldljTAc46c9hp34u',
        },
        authorship_hhmi: {
          name: 'authorship__hhmi',
          id: 'fld6VEsdkhscgc5TV',
        },
        authorships_author_display_name: {
          name: 'authorships.author.display_name',
          id: 'fld8Vr6YaYdmDSbq5',
        },
        authorships_author_orcid: {
          name: 'authorships.author.orcid',
          id: 'fldgK3MkbNBXUxWDl',
        },
        authorships_institutions_display_name: {
          name: 'authorships.institutions.display_name',
          id: 'fldragyWXvq3rrr8S',
        },
        authorships_institutions_ror: {
          name: 'authorships.institutions.ror',
          id: 'fld3859xP3VdtKlcx',
        },
        authorships_is_corresponding: {
          name: 'authorships.is_corresponding',
          id: 'fldhByITBhaRH1040',
        },
        bibliography_cross_check: {
          name: 'Bibliography Cross-Check',
          id: 'fldmYBs9KHHxHoUVf',
        },
        biorxiv_api_detail_url: {
          name: 'bioRxiv API Detail URL',
          id: 'fldyc12lRJk4HyBYu',
        },
        can_use_hhmi_funds: {
          name: 'Can Use HHMI Funds',
          id: 'fldkIlVXOttOOjbDp',
        },
        can_archive: {
          name: 'can_archive',
          id: 'fldLIOf9A63RRgKtN',
        },
        cc_review_team: {
          name: 'CC Review Team?',
          id: 'fldgE3h0N8aO2a4CJ',
        },
        check_scientists_flag: {
          name: 'Check Scientists Flag',
          id: 'fldIsxLEDB3nLjKOE',
        },
        cited_by_count: {
          name: 'cited_by_count',
          id: 'fldZZrPxfPhGEhyGm',
        },
        compliance_modified: {
          name: 'Compliance Modified',
          id: 'fldqvXT3wWAmd5z5d',
        },
        concepts_display_name: {
          name: 'concepts.display_name',
          id: 'fldo3B2UMrmhB0Gyb',
        },
        container: {
          name: 'Container',
          id: 'fldc1hin39fQZmcqy',
        },
        corresponding_author_orcids: {
          name: 'Corresponding Author ORCIDs',
          id: 'fldZONw9mbdirWyyH',
        },
        corresponding_review_year: {
          name: 'Corresponding Review Year',
          id: 'fldXVbepkoNCfJgdB',
        },
        created_time: {
          name: 'Created Time',
          id: 'fldt2DtX7Wgao2FNH',
        },
        crossref_api_link: {
          name: 'Crossref API Link',
          id: 'fldQgwmza8SHvEL6y',
        },
        date_resolved_for_interface: {
          name: 'Date Resolved for Interface',
          id: 'fldOt1Q5WVkIBDfNU',
        },
        days_from_preprint_v1_to_vor: {
          name: 'Days From Preprint v1 to VOR',
          id: 'fldwXCLlumpLdmP6i',
        },
        days_published_to_detected: {
          name: 'Days Published to Detected',
          id: 'fld9VAaIuqPgxxS7x',
        },
        doi: {
          name: 'DOI',
          id: 'fld6Yvyd93Viyrfq4',
        },
        email_template_link: {
          name: 'Email Template: Link',
          id: 'fldLr5nabFVDypc99',
        },
        email_template_markdown_formula: {
          name: 'Email Template: Markdown Formula',
          id: 'fldDyGtvpnG2Z9MxK',
        },
        emailed: {
          name: 'Emailed',
          id: 'fldvHlY42zwoYDJUm',
        },
        employee_ids: {
          name: 'Employee IDs',
          id: 'fldBAtGpuleuiLnaF',
        },
        estimated_next_review_date: {
          name: 'Estimated Next Review Date',
          id: 'fldHCbfmNgy9SLMuD',
        },
        estimated_next_review_fy: {
          name: 'Estimated Next Review FY',
          id: 'fldVwW6yiu9w3xLtj',
        },
        ever_non_compliant: {
          name: 'Ever Non-Compliant?',
          id: 'fldqSSi25Dor0ZOqu',
        },
        funder_name: {
          name: 'funder.name',
          id: 'fld0mXA2TkTkpKZ5I',
        },
        grantid_hhmi: {
          name: 'grantid__hhmi',
          id: 'fldJSRi1aL7sqnI5H',
        },
        has_data_availability_statement: {
          name: 'has_data_availability_statement',
          id: 'fldjiLbIm5ToRtMWe',
        },
        has_oa_locations_embargoed: {
          name: 'has_oa_locations_embargoed',
          id: 'fld8w07F5v8qJ5xRB',
        },
        has_preprint_copy: {
          name: 'has_preprint_copy',
          id: 'fld7mcvhiqQIVZH3Y',
        },
        is_after_last_review: {
          name: 'Is After Last Review?',
          id: 'fldhpWnZxCxAGm9uS',
        },
        is_between_reviews: {
          name: 'Is Between Reviews?',
          id: 'fldvaXHjc39xGY6cG',
        },
        is_last_year: {
          name: 'Is Last Year',
          id: 'fldGGaiTk5XVDz1Vm',
        },
        is_this_year: {
          name: 'Is This Year',
          id: 'fldW6xCDwjSb62ZHK',
        },
        is_compliant_with_2022_policy_hhmi: {
          name: 'is_compliant_with_2022_policy__hhmi',
          id: 'fldAvOPQMPU9Hm0rl',
        },
        is_compliant_with_old_policy_hhmi: {
          name: 'is_compliant_with_old_policy__hhmi',
          id: 'fldltJWK2JPv7OCUn',
        },
        is_covered_by_2022_policy_hhmi: {
          name: 'is_covered_by_2022_policy__hhmi',
          id: 'fldUiNvUFgOWJ5Hfm',
        },
        is_covered_by_old_policy_hhmi: {
          name: 'is_covered_by_old_policy__hhmi',
          id: 'fldq0Cbftc4gn5b9w',
        },
        is_oa: {
          name: 'is_oa',
          id: 'fldpAsL8AZQar1nWK',
        },
        is_original_research: {
          name: 'is_original_research',
          id: 'fldOvlnJqL2B2PTut',
        },
        issn: {
          name: 'issn',
          id: 'fldTBipmKRapQYLtf',
        },
        issue_type: {
          name: 'Issue Type',
          id: 'fldvkdf6x5F7Pkd85',
        },
        janelia_cross_check: {
          name: 'Janelia Cross-Check',
          id: 'fldauJRnBCL3ls8CW',
        },
        journal: {
          name: 'journal',
          id: 'fldFg35w4lB40X5lz',
        },
        journal_type: {
          name: 'Journal Type',
          id: 'fld68JGAq5rlERkM8',
        },
        journal_oa_type: {
          name: 'journal_oa_type',
          id: 'fldPBaJ2JtpphPbdb',
        },
        lab_heads_hhmi: {
          name: 'lab-heads__hhmi',
          id: 'fldgNN9aH3ygwSN2j',
        },
        last_date_emailed: {
          name: 'Last Date Emailed',
          id: 'fldUwIn6YrpvzGpca',
        },
        last_date_emailed_any_publication: {
          name: 'Last Date Emailed (Any Publication)',
          id: 'fldR8FBaXKXOZCBFJ',
        },
        last_name: {
          name: 'Last Name',
          id: 'fldSXXjbqtBPJuF4I',
        },
        last_review_date: {
          name: 'Last Review Date',
          id: 'fldsrwAScrDxNt5Ko',
        },
        linked_preprint: {
          name: 'Linked Preprint',
          id: 'fldKQtx1WSkTlxaJt',
        },
        linked_preprint_doi: {
          name: 'Linked Preprint DOI',
          id: 'flduSVKVXsPqNFg5J',
        },
        linked_preprint_doi_url: {
          name: 'Linked Preprint DOI URL',
          id: 'fldQmJ4L0hjzSxRt2',
        },
        linked_scientists: {
          name: 'Linked Scientists',
          id: 'fldoXPwmBuIeCUCcc',
        },
        location_resolved: {
          name: 'Location Resolved',
          id: 'fldW53a8FpcLn9fLF',
        },
        major_contribution: {
          name: 'Major Contribution',
          id: 'fld75gN28Ho6hNS2q',
        },
        modified_time: {
          name: 'Modified Time',
          id: 'fldOqbe6eeyuRCu0e',
        },
        non_compliant_all_time: {
          name: 'Non-Compliant All-Time',
          id: 'fldYIX9Il6CrbehjH',
        },
        non_compliant_current: {
          name: 'Non-Compliant Current',
          id: 'fld6lw79F6YJ1HF5h',
        },
        not_subject_to_policy_reason: {
          name: 'Not Subject to Policy Reason',
          id: 'fld38udeCBu3xF9pm',
        },
        notes: {
          name: 'Notes',
          id: 'fldB4F7yB1AyWovmJ',
        },
        number_of_journals: {
          name: 'Number of Journals',
          id: 'fldsO500dPADoXV9R',
        },
        number_of_lab_heads: {
          name: 'Number of Lab Heads',
          id: 'fldnEC14C4wVLmL1Q',
        },
        number_of_linked_scientists: {
          name: 'Number of Linked Scientists',
          id: 'fld8UKtvQKxoQ8l7p',
        },
        number_of_outreach_emails: {
          name: 'Number of Outreach Emails',
          id: 'fldSohAsg1P9YzMwS',
        },
        number_of_publishers: {
          name: 'Number of Publishers',
          id: 'fldhflxHWiqEf7Zne',
        },
        open_email: {
          name: 'Open Email',
          id: 'fldFGqpLb796GEucI',
        },
        openalex_api_link: {
          name: 'OpenAlex API Link',
          id: 'fldJ9fyH8AvJSBXB0',
        },
        openalx_open_access_any_repository_has_fulltext: {
          name: 'openalx.open_access.any_repository_has_fulltext',
          id: 'fldFP2DKSaJnXbzue',
        },
        openalx_open_access_oa_status: {
          name: 'openalx.open_access.oa_status',
          id: 'fld6QOZbby8MMxO4V',
        },
        outreach: {
          name: 'Outreach',
          id: 'fldVQyMX7EcBgx4GS',
        },
        pmc_days_in_status: {
          name: 'PMC Days in Status',
          id: 'fldmJV0T5wVzBkjIu',
        },
        pmc_submission: {
          name: 'PMC Submission',
          id: 'fldaMpt2t0Rt31qd8',
        },
        pmc_submission_date: {
          name: 'PMC Submission Date',
          id: 'fldA1aBpUJCA43QLJ',
        },
        pmc_submission_status: {
          name: 'PMC Submission Status',
          id: 'fldPqRD07w0mSj4iA',
        },
        pmc_submitter: {
          name: 'PMC Submitter',
          id: 'fldDABUF6fsERPre0',
        },
        pmc_url: {
          name: 'PMC URL',
          id: 'flduLM7onrAZV63eN',
        },
        pmc_pubmed_link: {
          name: 'PMC/PubMed Link',
          id: 'fldqP7iwBa7ssnHVO',
        },
        pmcid: {
          name: 'PMCID',
          id: 'fld4pGRXHKzruoymC',
        },
        pmid: {
          name: 'PMID',
          id: 'fldLqEOmCbUR2zuR8',
        },
        preprint_date_best: {
          name: 'Preprint Date (Best)',
          id: 'fldgnKUJW2WYWyqvB',
        },
        preprint_latest_date: {
          name: 'Preprint Latest Date',
          id: 'fldAyonh0evzBiXdn',
        },
        preprint_license: {
          name: 'Preprint License',
          id: 'fldU3ik6ttEkgcTHI',
        },
        preprint_url: {
          name: 'Preprint URL',
          id: 'fld8DLwXzSQyqxtDQ',
        },
        preprint_v1_date: {
          name: 'Preprint v1 Date',
          id: 'fld4uCd6o49dRXsZx',
        },
        preprint_versions: {
          name: 'Preprint Versions',
          id: 'fldvuHJr7wrTXFEVH',
        },
        preprint_doi: {
          name: 'preprint_doi',
          id: 'fldD7l0U2XzePfAQN',
        },
        preprint_authorship_hhmi: {
          name: 'Preprint: authorship__hhmi',
          id: 'flddAshGMuGX3QDcj',
        },
        preprint_linked_scientists: {
          name: 'Preprint: Linked Scientists',
          id: 'fldPvLb827EL8HfnS',
        },
        program: {
          name: 'Program',
          id: 'fldv2RmySjd8hBaRh',
        },
        published_date: {
          name: 'published_date',
          id: 'fldTjg7cJIVqP3TlN',
        },
        published_year: {
          name: 'published_year',
          id: 'fldGobcnzFSdCIKqK',
        },
        publisher: {
          name: 'publisher',
          id: 'fldD0UDFHrZ8R46rg',
        },
        publisher_url: {
          name: 'Publisher URL',
          id: 'fldmCVLd1qhZddg8v',
        },
        publisher_license_best: {
          name: 'publisher_license_best',
          id: 'fldc0q9YB5pVOLdNP',
        },
        pubtype: {
          name: 'pubtype',
          id: 'fld1Ub7fplRtM9MKU',
        },
        pubtype_crossref: {
          name: 'pubtype_crossref',
          id: 'fldGhTvnkAkPkKnDa',
        },
        query_openalex: {
          name: 'Query OpenAlex',
          id: 'fldfEQbonSH412a2Y',
        },
        repository_license_best: {
          name: 'repository_license_best',
          id: 'fldYiR3ADrUd6iOei',
        },
        repository_url: {
          name: 'repository_url',
          id: 'fldWRQjtK8Y4HsF3w',
        },
        repository_version: {
          name: 'repository_version',
          id: 'fld1NW7rTdx47lMcr',
        },
        responded: {
          name: 'Responded',
          id: 'fldmzGKHADZuQNazb',
        },
        review_reminder: {
          name: 'Review Reminder',
          id: 'fldxBZPrqt2fzo5qZ',
        },
        scientist_disciplines: {
          name: 'Scientist Disciplines',
          id: 'fldTTQ5loNKYeRNid',
        },
        scientist_email_s: {
          name: 'Scientist Email(s)',
          id: 'fld1wlN1mXw5T5DA3',
        },
        scientist_status: {
          name: 'Scientist Status',
          id: 'fldpWumlG3btQw45g',
        },
        similarity: {
          name: 'Similarity',
          id: 'fld7JAx2NhlDGK5k3',
        },
        similarity_explanation: {
          name: 'Similarity Explanation',
          id: 'fldJ0j7A0y2M0Az1u',
        },
        so_email: {
          name: 'SO Email',
          id: 'fld6q8hOMPb4qqViU',
        },
        start_date: {
          name: 'Start Date',
          id: 'fldWUPY6GVbGExrwL',
        },
        status: {
          name: 'Status',
          id: 'fld5w6DSuZHMn6rsi',
        },
        status_last_updated: {
          name: 'Status Last Updated',
          id: 'fldoXQzGA0gY3HLLK',
        },
        subject: {
          name: 'subject',
          id: 'fld9z1B9p4amhGpir',
        },
        submission_date: {
          name: 'submission_date',
          id: 'fldpfSH4F9SIoySUO',
        },
        title: {
          name: 'title',
          id: 'fldoKKBnR6Tj8vTFX',
        },
        top_level_compliance: {
          name: 'Top-Level Compliance',
          id: 'fldds3wSBeszTCV4l',
        },
        top_level_policy: {
          name: 'Top-Level Policy',
          id: 'fldgL8xwpEzAMpVaw',
        },
        url: {
          name: 'URL',
          id: 'fldJwCNizDOeWSMnQ',
        },
        version: {
          name: 'version',
          id: 'fldUWbrEi4eJficHh',
        },
        year: {
          name: 'Year',
          id: 'fld0E09Tqj365gW5i',
        },
      },
    },
    preprints: {
      name: 'Preprints',
      id: 'tblRWSiJvlOjt2OI4',
      fields: {
        abstract: {
          name: 'Abstract',
          id: 'fld4b6PxI70Ey4Hve',
        },
        abstract_similarity: {
          name: 'Abstract Similarity',
          id: 'fldZ0K6OMYmR7mYnN',
        },
        abstract_text: {
          name: 'Abstract Text',
          id: 'fldzKLuufo09Z0lbF',
        },
        action_steps: {
          name: 'Action Steps',
          id: 'fldwI1CD7u3ODxUCM',
        },
        ai_summary_from_abstract: {
          name: 'AI Summary (from Abstract)',
          id: 'fldZJjDEKsNQAFNMW',
        },
        all_dates_emailed: {
          name: 'All Dates Emailed',
          id: 'fld6Ym1c7jMHuBufc',
        },
        author_list_standardized: {
          name: 'Author List Standardized',
          id: 'fldz3wl0VVf1lo87Z',
        },
        authors: {
          name: 'Authors',
          id: 'fldegGBVQNqzpipx9',
        },
        authorship_hhmi: {
          name: 'authorship__hhmi',
          id: 'fldLcmwLDSx3xojix',
        },
        authorships_author_orcid: {
          name: 'authorships.author.orcid',
          id: 'fldZYKCfMqxkmoIa9',
        },
        authorships_is_corresponding: {
          name: 'authorships.is_corresponding',
          id: 'fldFAr9Qx6GO4yet9',
        },
        bibliography_cross_check: {
          name: 'Bibliography Cross-Check',
          id: 'fld4QW0rjWoYo9NSu',
        },
        blog_posts: {
          name: 'Blog posts',
          id: 'fld4Ta3AckQVBSIEt',
        },
        cc_review_team: {
          name: 'CC Review Team?',
          id: 'fldnjNNSYQPnusqjJ',
        },
        citations: {
          name: 'Citations',
          id: 'fld5WhoDZ2lfZA9bk',
        },
        comments: {
          name: 'Comments',
          id: 'fldewsPccpyp5smVo',
        },
        community: {
          name: 'Community',
          id: 'fldYzsAHCLSHGNseF',
        },
        corresponding_author_orcids: {
          name: 'Corresponding Author ORCIDs',
          id: 'fld6OiYkrRbXfwCzX',
        },
        corresponding_review_year: {
          name: 'Corresponding Review Year',
          id: 'fldWlCEaDHNbbHxMk',
        },
        count_publications: {
          name: 'Count Publications',
          id: 'fld3xPPca901hbAXx',
        },
        created_time: {
          name: 'Created Time',
          id: 'fldFkvqXtm19p9aNB',
        },
        crossref_api_link: {
          name: 'Crossref API Link',
          id: 'fldfPCK5RDjpw9wfU',
        },
        date: {
          name: 'Date',
          id: 'fld1F1mJLQHm1Uuou',
        },
        date_resolved_for_interface: {
          name: 'Date Resolved for Interface',
          id: 'fldKxbzXVhg8mKRsL',
        },
        days_from_preprint_v1_to_vor: {
          name: 'Days From Preprint v1 to VOR',
          id: 'fld9N5jVhupEEPC24',
        },
        doi: {
          name: 'DOI',
          id: 'fldN9ezAWRvPv9sNt',
        },
        elife_rp: {
          name: 'eLife RP',
          id: 'fldebwu31djOH5bLN',
        },
        email_template_link: {
          name: 'Email Template: Link',
          id: 'fldRiFo7xn5QMtJQO',
        },
        estimated_next_review_date: {
          name: 'Estimated Next Review Date',
          id: 'fldD3UXzOuU4t6i18',
        },
        estimated_next_review_fy: {
          name: 'Estimated Next Review FY',
          id: 'fldZJjHAaArOKFQaA',
        },
        ever_non_compliant: {
          name: 'Ever Non-Compliant?',
          id: 'flduTMMyGsrvhxcve',
        },
        full_text: {
          name: 'Full-text',
          id: 'fld2c0hIlrV0F7eOX',
        },
        is_between_reviews: {
          name: 'Is Between Reviews?',
          id: 'fldpTidJOmDaOku79',
        },
        is_last_year: {
          name: 'Is Last Year',
          id: 'fld7ALiQyCiwp5PG2',
        },
        is_this_year: {
          name: 'Is This Year',
          id: 'fldsENqLp9mtC4ygH',
        },
        is_compliant_with_2026_policy: {
          name: 'is_compliant_with_2026_policy',
          id: 'fldQHSJ8ZnNWrTPY0',
        },
        is_covered_by_2026_policy: {
          name: 'is_covered_by_2026_policy',
          id: 'fldw2eupAWTTI7bcd',
        },
        issue_type: {
          name: 'Issue Type',
          id: 'fldvOJtj1FM7WZVrt',
        },
        janelia_cross_check: {
          name: 'Janelia Cross-Check',
          id: 'fldTpa1VgG0I9akbk',
        },
        journal: {
          name: 'Journal',
          id: 'fld9tUjZ91YzELBkP',
        },
        lab_heads_hhmi: {
          name: 'lab-heads__hhmi',
          id: 'fld88ZvPCYBeiEqah',
        },
        last_date_emailed: {
          name: 'Last Date Emailed',
          id: 'fldAK49YnniFyWBNi',
        },
        last_date_emailed_any_publication: {
          name: 'Last Date Emailed (Any Publication)',
          id: 'fldz4tSb3kfiaEIbm',
        },
        last_name: {
          name: 'Last Name',
          id: 'fldAqXTPf9JnshbQK',
        },
        last_review_date: {
          name: 'Last Review Date',
          id: 'fldU3Dos74Rg2zPEt',
        },
        license: {
          name: 'License',
          id: 'fldBjBb7RyH3Y4Wp0',
        },
        license_standardized: {
          name: 'License Standardized',
          id: 'fldCXRTGUf0dExOyF',
        },
        linked_publication: {
          name: 'Linked Publication',
          id: 'fldxY0X621vSpooTk',
        },
        linked_scientists: {
          name: 'Linked Scientists',
          id: 'fldtlpVtAqV22zIgs',
        },
        major_contribution: {
          name: 'Major Contribution',
          id: 'fld2j44gvaFieKlwG',
        },
        modified_time: {
          name: 'Modified Time',
          id: 'fldmpuJPkQj6H9t0H',
        },
        msm: {
          name: 'MSM',
          id: 'fldqjiB0wQJNGqmKH',
        },
        not_subject_to_policy_reason: {
          name: 'Not Subject to Policy Reason',
          id: 'fldb9TOkf3pRrLgbW',
        },
        notes: {
          name: 'Notes',
          id: 'fldC41rIhR0MktOcr',
        },
        open_email: {
          name: 'Open Email',
          id: 'fldwz94LSv758Z5vH',
        },
        openalex_api_link: {
          name: 'OpenAlex API Link',
          id: 'fldZWPOjyYTw1KHG0',
        },
        outreach: {
          name: 'Outreach',
          id: 'fldIEk8eTkuXapDz9',
        },
        pdf: {
          name: 'PDF',
          id: 'fldPfvpkdUkWPL0Gy',
        },
        pmc_url: {
          name: 'PMC URL',
          id: 'fldUtxIi40lW73IKb',
        },
        pmcid: {
          name: 'PMCID',
          id: 'fldMjopooN3ylGyGj',
        },
        pmid: {
          name: 'PMID',
          id: 'fld2AyuiogV0lsPZ1',
        },
        preprint_v1_to_vor_group: {
          name: 'Preprint v1 to VOR Group',
          id: 'fldtlvsaVarGysj0L',
        },
        program: {
          name: 'Program',
          id: 'fldCbuqlUaCX1w9u3',
        },
        pub_date: {
          name: 'Pub Date',
          id: 'fld7PToWmhZCDSKt3',
        },
        publication_url: {
          name: 'Publication URL',
          id: 'fldVX7MqgBjJUAs5i',
        },
        publication_2022_compliance: {
          name: 'Publication: 2022 Compliance',
          id: 'flds9lZTl0dSaDvbi',
        },
        publication_2022_covered: {
          name: 'Publication: 2022 Covered',
          id: 'fldFCeaxbTMmBVEKR',
        },
        publication_action_steps: {
          name: 'Publication: Action Steps',
          id: 'fldSEWAtGxnsiaO86',
        },
        publication_authors: {
          name: 'Publication: Authors',
          id: 'fldj5AtAmZlzKuZxB',
        },
        publication_authorship_hhmi: {
          name: 'Publication: authorship__hhmi',
          id: 'fldt5gfWSPvV8VH7p',
        },
        publication_date: {
          name: 'Publication: Date',
          id: 'fldImyoOZ0a4bQz2f',
        },
        publication_issue_type: {
          name: 'Publication: Issue Type',
          id: 'fldW0SmHxoERgfSZj',
        },
        publication_license: {
          name: 'Publication: License',
          id: 'fldQq8YaQjTo6314Z',
        },
        publication_linked_scientists: {
          name: 'Publication: Linked Scientists',
          id: 'fldmA7OEzrM1jQS7M',
        },
        publication_not_subject_to_policy_reason: {
          name: 'Publication: Not Subject to Policy Reason',
          id: 'fldjWLS3bnc2y6ibQ',
        },
        publication_pmc_url: {
          name: 'Publication: PMC URL',
          id: 'fldviJbp3h8JpZuWA',
        },
        publication_pmcid: {
          name: 'Publication: PMCID',
          id: 'fldbZLDApI2WsL413',
        },
        publication_pmid: {
          name: 'Publication: PMID',
          id: 'fldZeoTmTJtM80hNG',
        },
        publication_publisher: {
          name: 'Publication: Publisher',
          id: 'fldJXJ3a71b39tvrV',
        },
        publication_status: {
          name: 'Publication: Status',
          id: 'fldHZ1oQcq3yIyI9c',
        },
        publication_title: {
          name: 'Publication: Title',
          id: 'fldaD9tDf5R19MkcB',
        },
        publication_top_level_policy: {
          name: 'Publication: Top-Level Policy',
          id: 'fldhszkUGiWG04DQw',
        },
        published_doi: {
          name: 'Published DOI',
          id: 'fldVcXzNjJVVk3hDA',
        },
        published_doi_url: {
          name: 'Published DOI URL',
          id: 'fldRQQTSNiZQGzck7',
        },
        publisher: {
          name: 'Publisher',
          id: 'fldv38ahq2YFkwqbi',
        },
        pubmed_url: {
          name: 'PubMed URL',
          id: 'fldqu9TdVI96mLXZW',
        },
        query_openalex: {
          name: 'Query OpenAlex',
          id: 'fldIt8NLphXWB8jKs',
        },
        responded: {
          name: 'Responded',
          id: 'fld7WZIn8PhZdeOVV',
        },
        review_reminder: {
          name: 'Review Reminder',
          id: 'fldTRnKZRX5EiWxW3',
        },
        scientist_email_s: {
          name: 'Scientist Email(s)',
          id: 'fldp36zJYHrDR2Fh1',
        },
        scientist_status: {
          name: 'Scientist Status',
          id: 'fldFUGtahPg1RCoqd',
        },
        score: {
          name: 'Score',
          id: 'fldex4GZCawqrmnKx',
        },
        server: {
          name: 'Server',
          id: 'fldYcpq5DigsUd9Es',
        },
        so_email: {
          name: 'SO Email',
          id: 'fldbJecA1Sp788e7u',
        },
        start_date: {
          name: 'Start Date',
          id: 'fldzNuLBvcZi81ghr',
        },
        status: {
          name: 'Status',
          id: 'fldUeNAIRdFmbYulm',
        },
        status_last_updated: {
          name: 'Status Last Updated',
          id: 'fldYzwQBIYgTNHQDW',
        },
        title: {
          name: 'Title',
          id: 'fldoK9FkXcWi4piR1',
        },
        top_level_compliance: {
          name: 'Top-Level Compliance',
          id: 'fldD1Iwvq0oBYcr0B',
        },
        top_level_covered: {
          name: 'Top-Level Covered',
          id: 'fldF3IFRrPYLUdr61',
        },
        top_level_policy: {
          name: 'Top-Level Policy',
          id: 'fld8y2w4QQ4JaZTFC',
        },
        top_level_title: {
          name: 'Top-Level Title',
          id: 'fldZm8i4IQuLRcSxQ',
        },
        trip: {
          name: 'TRiP',
          id: 'fldeQPRKsiW8Di9YX',
        },
        tweets: {
          name: 'Tweets',
          id: 'fldNQ8thUgxTcGZAw',
        },
        url: {
          name: 'URL',
          id: 'fldSzw2226rgUk9Zt',
        },
        version: {
          name: 'Version',
          id: 'fld0oeeelVyGE4tgN',
        },
        version_1_date: {
          name: 'Version 1 Date',
          id: 'fldTrrEvygCrHSOxB',
        },
        version_group: {
          name: 'Version Group',
          id: 'fldFNHvuP9M4aNXxT',
        },
        year: {
          name: 'Year',
          id: 'fldKYHNZLjn4hB32r',
        },
      },
    },
    scientists: {
      name: 'Scientists',
      id: 'tblKTlRedfiVcTo36',
      fields: {
        appointment_status: {
          name: 'Appointment Status',
          id: 'fldGx7ggebbUXSXpW',
        },
        cc_review_team: {
          name: 'CC Review Team?',
          id: 'fldzLKeAOtpLcSRoI',
        },
        compliance_rate_covered_preprints: {
          name: 'Compliance Rate - Covered Preprints',
          id: 'fldzq6MBbG3FWEG9I',
        },
        compliance_rate_covered_publications: {
          name: 'Compliance Rate - Covered Publications',
          id: 'fldGjMYuVmiuSR4xN',
        },
        compliance_rate_preprints: {
          name: 'Compliance Rate - Preprints',
          id: 'fldFLohCKTbJ3rdYx',
        },
        compliance_rate_publications: {
          name: 'Compliance Rate - Publications',
          id: 'fldXoQ2ecYpsgbNsa',
        },
        compliant_preprints: {
          name: 'Compliant Preprints',
          id: 'fldPwE8kD3r4NQrIG',
        },
        compliant_publications: {
          name: 'Compliant Publications',
          id: 'fld0GoHrTvqFMpNX7',
        },
        count_all_time_issues: {
          name: 'Count All-Time Issues',
          id: 'fldkKF9zNgnTn6R96',
        },
        created_time: {
          name: 'Created Time',
          id: 'fldOPdnF4Fj4WBjj7',
        },
        discipline_combined: {
          name: 'Discipline, Combined',
          id: 'fldOl9SJ2JGzfj83l',
        },
        discipline_primary: {
          name: 'Discipline, Primary',
          id: 'fldkBwRDrlvRkEVKr',
        },
        discipline_secondary: {
          name: 'Discipline, Secondary',
          id: 'fldirWq2B9t3CnmCl',
        },
        email: {
          name: 'Email',
          id: 'fldiIBY4VDx70todG',
        },
        employee_hire_date: {
          name: 'Employee - Hire Date',
          id: 'fldjpx0ZiLFZIXpbv',
        },
        employee_id: {
          name: 'Employee ID',
          id: 'fldb6uul1jo8tBmpI',
        },
        fhs_hire_date: {
          name: 'FHS - Hire Date',
          id: 'fldFNqIAfkzq5M0qT',
        },
        first_name_preferred: {
          name: 'First Name (Preferred)',
          id: 'fldn07q9nSQdHJzv1',
        },
        first_name_primary: {
          name: 'First Name (Primary)',
          id: 'flds2taPaXCUmNB3n',
        },
        full_name_primary: {
          name: 'Full Name (Primary)',
          id: 'fldGfKWEzaydmQt7O',
        },
        full_name_with_preferred: {
          name: 'Full Name with Preferred',
          id: 'fldHtCTB23QbZrjFs',
        },
        hide_in_interface: {
          name: 'Hide in Interface',
          id: 'fld2N8E7jt8hBXHew',
        },
        hire_date_best: {
          name: 'Hire Date Best',
          id: 'fldDc1fxtgQRJtwfr',
        },
        iar_review_reminder_sent: {
          name: 'IAR Review Reminder Sent',
          id: 'fldEZuv2JsoCsbut9',
        },
        iar_review_reminder_template: {
          name: 'IAR Review Reminder Template',
          id: 'fldIqSy3wrESOHG2J',
        },
        institution: {
          name: 'Institution',
          id: 'fldbCeK8vxMzXfY3Z',
        },
        investigator_current_end_date: {
          name: 'Investigator - Current End Date',
          id: 'fldos7Z0oRFfp3or1',
        },
        investigator_estimated_next_review_date: {
          name: 'Investigator - Estimated Next Review Date',
          id: 'fldWYBYulRgPf0s7P',
        },
        investigator_estimated_next_review_fy: {
          name: 'Investigator - Estimated Next Review FY',
          id: 'fldgAOCZPZMdQC0cF',
        },
        investigator_hire_date: {
          name: 'Investigator - Hire Date',
          id: 'fldM5Pe9TnvNlD3j5',
        },
        investigator_rehire_date: {
          name: 'Investigator - Rehire Date',
          id: 'fldl1uQlOVNsWC5YI',
        },
        labarchives_access: {
          name: 'LabArchives Access',
          id: 'fldFV17b89R581I02',
        },
        last_date_emailed_any_publication: {
          name: 'Last Date Emailed (Any Publication)',
          id: 'fldQdjyPk9hFRmH5E',
        },
        last_name_preferred: {
          name: 'Last Name (Preferred)',
          id: 'fld3MnNgCgzAhULc2',
        },
        last_name_primary: {
          name: 'Last Name (Primary)',
          id: 'fldnQGqNDAOURz9Rb',
        },
        last_review_date: {
          name: 'Last Review Date',
          id: 'fldTlqumFOA6LGrhT',
        },
        major_contributions: {
          name: 'Major Contributions',
          id: 'fldsMzjOqLb8sCucC',
        },
        major_contributions_with_preprints: {
          name: 'Major Contributions with Preprints',
          id: 'fldToKFTkX2BjhDO0',
        },
        major_preprints_in_2026: {
          name: 'Major Preprints in 2026',
          id: 'fld6MSKtype597SC5',
        },
        max_preprint_version: {
          name: 'Max Preprint Version',
          id: 'fldtQ65FNPN9Osaij',
        },
        middle_name_preferred: {
          name: 'Middle Name (Preferred)',
          id: 'fld9LxLBGozdXVpwV',
        },
        middle_name_primary: {
          name: 'Middle Name (Primary)',
          id: 'fldKkyLX58mjI7yAv',
        },
        modified_time: {
          name: 'Modified Time',
          id: 'fldZcMbzmPrvB0Q1B',
        },
        modified_time_all_except_so: {
          name: 'Modified Time - All Except SO',
          id: 'fld74bHrMZAv1jMIc',
        },
        most_recent_competition: {
          name: 'Most Recent Competition',
          id: 'fldBOZkNHyhRpw5O6',
        },
        next_review_within_2_years: {
          name: 'Next Review Within 2 Years',
          id: 'fldbqtOfcSX6XdlpE',
        },
        nihms_grant_id: {
          name: 'NIHMS Grant ID',
          id: 'fldvUL6KgO08sR1da',
        },
        non_compliant_all_time_preprint_pmids: {
          name: 'Non-Compliant All-Time Preprint PMIDs',
          id: 'fldP6FKIwz8H8WrwY',
        },
        non_compliant_all_time_preprints: {
          name: 'Non-Compliant All-Time Preprints',
          id: 'fldUx2PNo3LhBvg5S',
        },
        non_compliant_all_time_publication_pmids: {
          name: 'Non-Compliant All-Time Publication PMIDs',
          id: 'fldPGuUnTzcePJ0mW',
        },
        non_compliant_all_time_publications: {
          name: 'Non-Compliant All-Time Publications',
          id: 'fld6F7YJHaGhDQ21s',
        },
        non_compliant_preprints: {
          name: 'Non-Compliant Preprints',
          id: 'fldpL9gRa6CdKOXda',
        },
        non_compliant_preprints_all_time_correspondence: {
          name: 'Non-Compliant Preprints All-Time Correspondence',
          id: 'fldHrord0LXwNVnzO',
        },
        non_compliant_preprints_all_time_issues: {
          name: 'Non-Compliant Preprints All-Time Issues',
          id: 'fldJCRIcS7zam1zn0',
        },
        non_compliant_preprints_all_time_status: {
          name: 'Non-Compliant Preprints All-Time Status',
          id: 'fldw39xP7dHlx9J1I',
        },
        non_compliant_publications: {
          name: 'Non-Compliant Publications',
          id: 'fldXtAFxTGYncI9Mf',
        },
        non_compliant_publications_all_time_correspondence: {
          name: 'Non-Compliant Publications All-Time Correspondence',
          id: 'fldDPrQ1cQHaFB3P2',
        },
        non_compliant_publications_all_time_issues: {
          name: 'Non-Compliant Publications All-Time Issues',
          id: 'fld8XTUeLJvI9mqzm',
        },
        non_compliant_publications_all_time_status: {
          name: 'Non-Compliant Publications All-Time Status',
          id: 'fldP2izWDgzbG3dKF',
        },
        open_email: {
          name: 'Open Email',
          id: 'fldO6pt85q8gUbs1T',
        },
        orcid_identifier: {
          name: 'ORCID Identifier',
          id: 'fldRrnnHqTrUS10cv',
        },
        orcid_link: {
          name: 'ORCID Link',
          id: 'fldBylHnr93dvouXe',
        },
        originally_compliant_preprints: {
          name: 'Originally Compliant Preprints',
          id: 'fldMpmApJwpw0ZpXv',
        },
        originally_compliant_publications: {
          name: 'Originally Compliant Publications',
          id: 'fldaOxw269nsW0Q9t',
        },
        outreach: {
          name: 'Outreach',
          id: 'fldY00S7Fq2VYYhEY',
        },
        parent_organization: {
          name: 'Parent Organization',
          id: 'fldo6v45iiGRYBt0O',
        },
        parent_ror: {
          name: 'Parent ROR',
          id: 'fldgdImuZT9PvDOHJ',
        },
        person_id: {
          name: 'Person ID',
          id: 'fld62qs4CJoy0dJRW',
        },
        preprint_rate: {
          name: 'Preprint Rate',
          id: 'fldOEMLkiLM8smuzH',
        },
        preprints: {
          name: 'Preprints',
          id: 'fldkWMrNWG1JZXpye',
        },
        program: {
          name: 'Program',
          id: 'fldTkV8fHLcxcNwkU',
        },
        publications: {
          name: 'Publications',
          id: 'fldaU7OszwvSiP90c',
        },
        reached_out_about_significant_articles: {
          name: 'Reached Out About Significant Articles?',
          id: 'fldU13fcREatbc9KK',
        },
        resolved_preprints: {
          name: 'Resolved Preprints',
          id: 'fld3GlVCACFf4WmGZ',
        },
        resolved_publications: {
          name: 'Resolved Publications',
          id: 'fld4UY5JgfKO5WbbO',
        },
        ror: {
          name: 'ROR',
          id: 'fldveoFqRzUbHUzqt',
        },
        scientific_officer: {
          name: 'Scientific Officer',
          id: 'fldcHo1Jhxa78hFpp',
        },
        scientist_id: {
          name: 'Scientist ID',
          id: 'fld5hV2FlCk511YrQ',
        },
        so_email: {
          name: 'SO Email',
          id: 'fldmBiIeNcBJYKzib',
        },
        status_modified_time: {
          name: 'Status Modified Time',
          id: 'fldEdRdIZewk2eeNu',
        },
        status_or_orcid_modified: {
          name: 'Status or ORCID Modified',
          id: 'fldTVP6rBIN7Zba58',
        },
        suffix: {
          name: 'Suffix',
          id: 'fldKbRKk61kes9CYO',
        },
        total_preprints: {
          name: 'Total Preprints',
          id: 'fldYkuONePZXcq6Xb',
        },
        total_preprints_subject_to_policy: {
          name: 'Total Preprints Subject to Policy',
          id: 'fldZAyWWQgW29cahd',
        },
        total_publications: {
          name: 'Total Publications',
          id: 'fldfnKggX4Vbkgg1S',
        },
        total_publications_subject_to_policy: {
          name: 'Total Publications Subject to Policy',
          id: 'fld9wBEx4GMH6NB5O',
        },
      },
    },
    journals: {
      name: 'Journals',
      id: 'tblIzVg2kQxXa5Xac',
      fields: {
        checker_tool: {
          name: 'Checker Tool',
          id: 'fldKH7uQtTS8lwZiL',
        },
        created_time: {
          name: 'Created Time',
          id: 'fldYDUptjzHL8xnbi',
        },
        feedback: {
          name: 'Feedback',
          id: 'fldwD2I4HqLuv99Mg',
        },
        issn_online: {
          name: 'ISSN (online)',
          id: 'fldnkzWJZX4sNgtxe',
        },
        issn_print: {
          name: 'ISSN (print)',
          id: 'fldXsKaNmfwiCJA3C',
        },
        journal_name: {
          name: 'Journal Name',
          id: 'fldKfNhrDXUCwYpeZ',
        },
        major_contributions_2024_2025: {
          name: 'Major Contributions 2024-2025',
          id: 'fldmCqbzaL6HkRfoc',
        },
        modified_time: {
          name: 'Modified Time',
          id: 'flddRNM87d90HF8HG',
        },
        nlm_abbreviation: {
          name: 'NLM Abbreviation',
          id: 'fldqrjuCmg8ZgeA6t',
        },
        nlm_unique_id: {
          name: 'NLM Unique ID',
          id: 'fldaxDubiXEKLKAJI',
        },
        number_of_publications: {
          name: 'Number of Publications',
          id: 'fldBxTHgyDYTaemUH',
        },
        number_of_publishers: {
          name: 'Number of Publishers',
          id: 'fldt9cYwpThER4L6s',
        },
        other_abbreviation: {
          name: 'Other Abbreviation',
          id: 'flddpZQeDlQVmZzTC',
        },
        payment_instruction_override: {
          name: 'Payment Instruction Override',
          id: 'fldhyh94GCW5VYdMr',
        },
        payment_policy: {
          name: 'Payment Policy',
          id: 'fldO9XA43Yc7IJ2yr',
        },
        pmc_agreement_status: {
          name: 'PMC Agreement Status',
          id: 'fldybWGyYGXC4qBCr',
        },
        pmc_agreement_to_deposit: {
          name: 'PMC Agreement to Deposit',
          id: 'fldSMNCAvJ9OMH5lu',
        },
        pmc_embargo: {
          name: 'PMC Embargo',
          id: 'fldD0I3I0SOBwRvm3',
        },
        pmc_url: {
          name: 'PMC URL',
          id: 'fldqtXSJ9DS34YTrN',
        },
        preprints: {
          name: 'Preprints',
          id: 'fld7BVqnnZZ6rFkcq',
        },
        publications: {
          name: 'Publications',
          id: 'fldcmt4OB7uqlYDc4',
        },
        publisher: {
          name: 'Publisher',
          id: 'fldwAkPbaMMwIrza1',
        },
        type: {
          name: 'Type',
          id: 'fldEsReawHiCqCHUS',
        },
      },
    },
  },
};
